// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtwtzq4RerDhgsHxNTfiPdITyNugQMFJU',
    appId: '1:417309941793:web:fdb5cc23d60e256e330360',
    messagingSenderId: '417309941793',
    projectId: 'tender-fire-demo',
    authDomain: 'tender-fire-demo.firebaseapp.com',
    storageBucket: 'tender-fire-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW7VbEMsIuvJnicoeR6A6jwMPJjNynfNM',
    appId: '1:417309941793:android:6199d3ded72a0fd6330360',
    messagingSenderId: '417309941793',
    projectId: 'tender-fire-demo',
    storageBucket: 'tender-fire-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYFp_ZqvoOB2vpz7EAZafOQdBndzq0Ynw',
    appId: '1:417309941793:ios:f587a6fb8ca7ad06330360',
    messagingSenderId: '417309941793',
    projectId: 'tender-fire-demo',
    storageBucket: 'tender-fire-demo.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYFp_ZqvoOB2vpz7EAZafOQdBndzq0Ynw',
    appId: '1:417309941793:ios:a5303b1dab85494e330360',
    messagingSenderId: '417309941793',
    projectId: 'tender-fire-demo',
    storageBucket: 'tender-fire-demo.appspot.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
